### ISSUE TITLE
Cant POST to authentication database

### ISSUE THREAD

**Issue by lipovac** [eigenfoo/euphoria#22]
We're missing a POST method in AuthenticationHandlers.java

**Comment by eigenfoo** [comment]
Relevant line(s):
https://github.com/eigenfoo/euphoria/blob/master/euphoria-service/src/main/java/edu/cooper/ece366/euphoria/AuthenticationHandlers.java#L27

**Comment by eigenfoo** [comment]
Closed by #23.
