### ISSUE TITLE
Use a request payload rather than multiple path args

### ISSUE THREAD

**Issue by luster** [eigenfoo/euphoria#34]
https://github.com/eigenfoo/euphoria/blob/master/euphoria-service/src/main/java/edu/cooper/ece366/euphoria/UserHandlers.java#L31

Style-wise, creating a new db object would usually be from a request payload.

See https://github.com/dhvanilshah/Symmetric-Social-Network-ECE366/issues/5 for an example

**Comment by eigenfoo** [comment]
Just need @lipovac to modify the frontend to make the correct http requests now.
