### ISSUE TITLE
Applications database doesnt contain application parameters

### ISSUE THREAD

**Issue by lipovac** [eigenfoo/euphoria#51]
Files, etc

@wside

**Comment by lipovac** [comment]
Could we also make retrieving the applications also retrieve the user email and phone number from the user database? Id have to make n http requests on my side if we dont

**Comment by wside** [comment]
Applications DB does not need resume or cover letter fields since they are the files are stored in the file system under the name resume_applicationId or cover_applicationId.

**Comment by wside** [comment]
the GET application call returns the userId. Use that to qury the user database for user email and phone number. Two separate calls keeps things more modular.

**Comment by eigenfoo** [comment]
Seconded. It's only two requests per posting and shouldn't be too much work. We agreed to structure the database for this reason: it is better to keep users separate from applications (since one user can have many applications), even at the expense of more busywork while querying.

**Comment by eigenfoo** [comment]
@lipovac closing this issue: it's just an actionable for you now.

**Comment by eigenfoo** [comment]
Reopening and placing on roadmap for final deadline.

**Comment by lipovac** [comment]
Ill make a call per application, all good
