### ISSUE TITLE
BLD: handle concurrent requests

### ISSUE THREAD

**Issue by eigenfoo** [eigenfoo/euphoria#59]
From the initial implementation spec:

> Your server should be able to handle concurrent user requests. Hint: you may want to use a connection pooling library if you’re using JDBC and Java. We will NOT be load testing your server at this stage however.

**Comment by eigenfoo** [comment]
@luster would you suggest [Apache DBCP](https://commons.apache.org/proper/commons-dbcp/download_dbcp.cgi) as a suitable connection pooling library for us? AFAICT there isn't an example of connection pooling in the `bookstore` example, so I'm trying to understand what needs to be done.

**Comment by luster** [comment]
DBCP looks fine. Use whatever looks easiest to implement
